### PR TITLE
Go BLUI

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Go BLUI

### CODE REVIEW

**Review by jeffvg — APPROVED** [review]

**Comment by daileytj** [comment]
Some screenshots of not-so-great things I found... This is on a 7th gen iPod touch btw. That was the device it defaulted to open in, but the device width is quite small.

Landing page header overflow
Simulator Screen Shot - iPod touch (7th generation) - 2021-12-06 at 14 51 06
Landing page horizontal scroll
Simulator Screen Shot - iPod touch (7th generation) - 2021-12-06 at 14 51 14
Sortable list icon
Simulator Screen Shot - iPod touch (7th generation) - 2021-12-06 at 14 50 53

**Comment by jeffvg** [comment]
ionic cordova run ios --list
ionic cordova run ios --target=XXXXXXX-XXXX-XXXX-XXXX-XXXXXXX

**Comment by emclaug2** [comment]
> Some screenshots of not-so-great things I found... This is on a 7th gen iPod touch btw. That was the device it defaulted to open in, but the device width is quite small. If these issues have been here the whole time, I'm happy to have to approve and have bugs written up to fix these since I doubt many people are even using these.

I'm happy to go back and make some issues for these; I'm thinking these are things that were already present in the ionic design patterns.

**Review by daileytj — APPROVED** [review]

**Comment by daileytj** [comment]
The green button is all yours @emclaug2

**Pull request merged**
